eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: localhost
spring:
  application:
    name: like-service
  cloud:
    discovery:
      enabled: true
  data:
    mongodb:
      database: user_db
      port: 27017
      host: localhost
server:
  port: 3020
management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  circuitBreaker:
    enable: true
logging:
  file:
    name: D:/Maveric/like-service/logs/likelog.log